name: playwright tests in docker

on: workflow_dispatch

jobs:
  pw-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run script
        run: npm run e2e:docker

      - name: copy report from container
        run: npm run docker:copyReport
      
      - name: Publish HTML report
        if: always()
        uses: actions/github-pages@v4
        with:
          branch: gh-pages
          folder: test-results/mochawesome
