name: playwright tests in docker

on: workflow_dispatch

jobs:
  pw-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run script
        run: npm run e2e:docker

      - name: copy report from container
        run: npm run docker:copyReport

      - name: Publish HTML report
        if: always() # We want this to always run, even if test fail prior to this step running
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: playwright-report
          keep_files: true 

      